services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: turnos
      MYSQL_USER: turnos
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
